# Generated by Django 2.1 on 2021-04-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ga', 'Irish'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('pt', 'Portuguese')], max_length=7)),
                ('artist', models.ManyToManyField(blank=True, null=True, related_name='language', to='resume.Artist')),
            ],
        ),
    ]
